export const LOAD_EVENT = 'svg-component:reload'
export const MODULE_NAME = '~virtual/svg-component'
export const USED_SVG_NAMES_FLAG = 'all'
export const PLUGIN_NAME = 'unplugin-svg-component'
export const SVG_COMPONENT_D_TS = 'svg-component.d.ts'
export const SVG_COMPONENT_GLOBAL_D_TS = 'svg-component-global.d.ts'
