export const LOAD_EVENT = 'svg-component:reload'
export const UPDATE_EVENT = 'svg-component:update'
export const MODULE_NAME = 'virtual:svg-component'
export const XMLNS = 'http://www.w3.org/2000/svg'
export const XMLNS_LINK = 'http://www.w3.org/1999/xlink'
