import { MODULE_NAME } from './constants'

const dtsComments = `
/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
`.trim()

export const template = `
  <svg 
    xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink" 
    style="$component_style"
    $component_class
    v-on="$listeners"
  >
    <use :xlink:href="'#' + name" />
  </svg>
`
export const dts = `${dtsComments}
declare module '${MODULE_NAME}' {
  const $component_name: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"$svg_symbolIds">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"$svg_symbolIds">;
          default: string;
          required: true;
      };
  }>>, {
      name: "$svg_symbolIds";
  }>;
  export const svgNames: ["$svg_names"];
  export type SvgName = "$svg_symbolIds";
  export default $component_name;
}
`

export const golbalDts = `${dtsComments}
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    $component_name: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"$svg_symbolIds">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"$svg_symbolIds">;
            default: string;
            required: true;
        };
    }>>, {
        name: "$svg_symbolIds";
    }>;
  }
}
`

export const reactTemplate = `
import React from 'react';

export default function $component_name({name,style,className}) {
  return React.createElement("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    xmlnsXlink: "http://www.w3.org/1999/xlink",
    style: {...$component_style, ...style},
    className: [className, $component_class || ''].filter(cls=> !!cls).join(" ") || undefined,
  }, React.createElement("use", {
    xlinkHref: "#" + name
  }));
}
`
export const reactDts = `${dtsComments}
declare module '${MODULE_NAME}' {
  const $component_name: (props: {
    name: "$svg_symbolIds"
    className?: string
    style?: React.CSSProperties
  }) => JSX.Element;
  export const svgNames: ["$svg_names"];
  export type SvgName = "$svg_symbolIds";
  export default $component_name;
}
`
