/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const MySvgIcon: (props: {
    name: "icon-icon-addUser" | "icon-icon-barCode" | "icon-icon-card2" | "icon-react"
    className?: string
    style?: React.CSSProperties
  }) => JSX.Element;
  export const svgNames: ["icon-icon-addUser", "icon-icon-barCode", "icon-icon-card2", "icon-react"];
  export type SvgName = "icon-icon-addUser" | "icon-icon-barCode" | "icon-icon-card2" | "icon-react";
  export default MySvgIcon;
}
